sourcegraph/conc

pool/error_pool.go
pool/pool.go

In the configuration methods, we dereference pools to copy them into the parent struct. This triggers the copylock lint. Even though it shouldn't actually be a problem because you shouldn't be configuring the pool after using the pool, it's still misleading and makes developing on conc noisy.

Avoid dereferencing to appease the copylock lint

---

README.md

@michaellzc found it suboptimal that an easily copy-pastable `go get` wasn't available 🙃

doc: add copy-pastable 'go get' to README

---

pool/context_pool_test.go
pool/result_context_pool_test.go
pool/result_error_pool_test.go

This has been a long-standing discussion (https://github.com/golang/go/issues/20733, https://github.com/golang/go/discussions/56010) but today, variables in iterations are per-loop, not per-iteration, so you need to copy these values for them to be used inside `p.Go`.
Add a `t.Log` inside `p.Go` in the corresponding tests to see that previously, we're always comparing against the last value in the iteration, i.e. 100, and after the change the correct value is used:
<table>
<tr>
<th>before - always the last value</th>
<th>after - uses the correct value</th>
</tr>
<tr>
<td>
```
=== CONT  TestContextPool/limit/100
context_pool_test.go:128: 100
=== CONT  TestContextPool/limit/10
context_pool_test.go:128: 100
=== CONT  TestContextPool/limit/100
context_pool_test.go:128: 100 …
```

pool: fix loop variables in tests

---

README.md

Since this repo got publicized a little before it had the opportunity to be tested rigorously internally, it's only fair to call out that there may be changes to the public API until we stabilize on a 1.0 release.

Add status blurb to the README

---

waitgroup.go

The zero-value of a WaitGroup is usable, but we have a constructor to parallel the construction of pools and streams. This might be confusing, so this clarifies in the WaitGroup docs that it works similarly to sync.WaitGroup.

Add note to WaitGroup docs about zero values and copying

---

pool/context_pool.go
pool/context_pool_test.go
pool/result_context_pool.go
pool/result_context_pool_test.go

This adds the `WithCancelOnError()` configuration method to `ContextPool` and `ResultContextPool`, and changes the default behavior to not cancel the pool's context on error.
`ContextPool` initially canceled by default because otherwise, it's no different than an `ErrorPool` that captures a context from its environment. However, doing this by default is surprising and should be explicitly opt-in.

Add CancelOnError option to ContextPool

---

README.md

The `stdlib` example in demonstrate `iter.ForEach` missed cleanup `channel` afterwards

doc: fix missing resource cleanup in README

---

README.md

Omitting the version automatically points to the latest version, i.e. https://pkg.go.dev/github.com/sourcegraph/conc/pool#Pool

doc: do not include version in godoc links

---

README.md
go.mod
go.sum
panic.go
panics/panics.go
panics/panics_test.go
stream/stream.go
waitgroup.go

Proposal: move `conc.PanicCatcher` to a subpackage, `conc/panics.Catcher`. We cannot use `panic` as a package name without conflicting with the builtin `panic()`.
IMO it is a bit strange for `PanicCatcher` to be part of the top-level `conc` package, since:
1. Most users of `conc.WaitGroup`, `conc/pool`, etc will never interact directly with panic catcher
2. While `PanicCatcher` can be used multiple times and concurrently, it only ever retains a single panic, so regardless of safety, in a standalone usecase I imagine one might use an instance of `PanicCatcher` for one goroutine at a time to get more granular `RecoveredPanic`s, so it doesn't really fit in with the theme of `conc` and is more of a utility.

panics: move PanicCatcher to separate package

---

waitgroup.go
waitgroup_test.go

Resolves #29.
👋 My attempt at resolving #29. I wasn't sure if was better to reimplement `Wait` in terms of `WaitSafe`. I think leaving the code as it looks a bit cleaner, so I just left it.
I also wondered if it is better to say in the docs that `WaitSafe` will return the first panic it encounters and add a test for that. That is true, right?
Thank you!

Add WaitAndRecover method to WaitGroup

---

iter/iter.go
iter/iter_test.go

Adds configurable concurrency to `iter` via a new type `Iterator` with ~no overhead and no API changes:
```go
customIterator := iter.Iterator{MaxGoroutines: 42}
customIterator.ForEach(...)
// zero value is safe, defaults to runtime.GOMAXPROCS(0)
iter.Iterator{}.ForEach(...)
// package-level functions behave the same as before
iter.ForEach(...)
```
If the API is agreeable, I can make a follow-up PR to introduce something similar for `Map` and friends. Note that `Map` cannot simply be a method on `Iterator` because methods cannot accept type parameters, and we do not want the return type `R` on `Iterator` where `ForEach` does not use `R`.
Relevant to https://github.com/sourcegraph/conc/issues/36, closes https://github.com/sourcegraph/conc/issues/55
---
Before:
```
go test -run=XXX -bench=. …
```

iter: introduce Iterator with configurable concurrency

---

pool/context_pool.go
pool/error_pool.go
pool/pool.go
pool/result_context_pool.go
pool/result_error_pool.go
pool/result_pool.go
stream/stream.go

A call to `Go()` will block if all the goroutines in the underlying pool are already handling a task. This documents that behavior. 
Fixes #61

Document that Go() blocks until the task can be started

---

iter/iter_test.go
iter/map.go
iter/map_test.go

This follows up https://github.com/sourcegraph/conc/pull/63 by introducing a `Mapper` type that can be used to configure mapping behaviour, while keeping the top-level `Map` and `MapErr` functions.
Relevant to https://github.com/sourcegraph/conc/issues/55
Stacked on https://github.com/sourcegraph/conc/pull/67
<details>
<summary>Previous discussion points</summary>
All superseded by https://github.com/sourcegraph/conc/pull/68#issuecomment-1384393956
the `Mapper` type must be a struct - IMO this type only really needs to be an `Iterator` with a result type `R`, defined as a type alias:
```go
type Mapper[T, R any] = Iterator[T]
```
This would reinforce that `Mapper` is simply an `Iterator` that also works with result types, and shouldn't have additional behaviours/state that might be better …

iter: introduce Mapper type with configurable Iterator

---

panics/panics.go

There is no longer a `.Value()` on `panics.Catcher`, presumably this is what `.Recovered()` used to be

panics: fix outdated reference to Recovered()

---

pool/error_pool.go
pool/pool.go
pool/result_error_pool.go
pool/result_pool.go

The docstrings still imply `ContextPool` always cancels on first error, which is no longer the case as of https://github.com/sourcegraph/conc/pull/23

pool: update docstrings on WithContext

---

panics/panics.go
panics/panics_test.go

Returning a concrete type `*RecoveredPanic` that implements `error` introduces an interesting gotcha - it looks like an `error` and behaves like an `error`, but cannot really be used as an error, because if returned as an error even if nil it's a typed error or something and shows up as _not nil_.
Example using the existing implementation:
```go
func TestCatcherRecovered(t *testing.T) {
var fn = func() error {
var c Catcher
c.Try(func() {})
return c.Recovered() // ok, looks like an error
}
err := fn()
assert.Nil(t, err)     // ok, surely no error
assert.NoError(t, err) // fails!! err is nil but is not a nil error
// Error: Received unexpected error:
//   	  <nil>
}
```
Playground example: https://go.dev/play/p/C1DAdBWY9EZ , example in practice: …

panics: allow usage of RecoveredPanic as a normal error

---

panics/try.go
panics/try_test.go

`panics` is pretty useful for cases where you're dealing with a third-party library that panics instead of handling errors, which is sadly a non-zero number of libraries. For one-off usages, however, using `Catcher` is clunky because it's designed to be reused - this adds a convenience function `Try` that attempts a single function and recovers from panics it raises.

panics: add single-fn Try at package level

---

README.md

example for iter.Map, function handler args is a pointer

fix readme example: iter.Map arg err

---

pool/context_pool.go

Now that we [no longer cancel-on-error by default](#23), it's possible that a `ContextPool` can be consumed without ever cancelling its context, which causes a goroutine leakage - this change ensures that we call `p.cancel()` (which can safely be called multiple times) on `p.Wait()`.
Alternatively, we could also only configure a cancellable context when the user calls `p.WithCancelOnError()`, but the discussion over at https://github.com/sourcegraph/conc/issues/86#issuecomment-1422595564 indicates that there is a strong desire for the ability to cancel a `ContextPool` without providing an additional context, so I decided not to go this route for now.
No additional tests because there should be no behaviour changes/additions.

pool: ensure ContextPool.cancel() is called

---

pool/context_pool.go
pool/context_pool_test.go
pool/result_context_pool_test.go

On `(*ContextPool).WithCancelOnError()` task errors, we cancel the context - but what if a task _panics_? I think it might be reasonable to assume that this will trigger a context cancellation since a panic is broadly an "error". This isn't the case in the current implementation, because a panic will abort before `ContextPool`'s error handling - if one task panics, other tasks will continue.
This change proposes that we catch panics separately for the `(*ContextPool).WithCancelOnError()` case, which allows us to cancel the pool's context before propagating the panic.

pool: let WithCancelOnError also cancel on panics

---

panics/panics.go
panics/panics_test.go
panics/try.go
waitgroup.go

Renames `panics.RecoveredPanic` and friends, which stutters somewhat, to just `panics.Recovered`.

panics: reduce naming stutter in panics.RecoveredPanic

---

panics/panics_test.go
pool/context_pool_test.go

I think we need an example of, if the tasks return before the context cancelled due to timeout, it should success

Added successful case for context pool, returns before timeout

---

pool/pool.go

For "unlimited" pools, in the [original code](https://github.com/sourcegraph/conc/blob/main/pool/pool.go#L45):
```go
p.handle.Go(p.worker)
p.tasks <- f
```
If in between the call to `handle.Go` and sending the task to the worker, another goroutine would call `pool.Go`, that task would "hijack" the newly created worker, causing the original send to block. This is undesirable behavior if the pool is unlimited.
The solution was to add an `initialFunc` to the worker, which will be executed before the worker starts waiting for new tasks. This ensures that a worker will first complete the task it was supposed to, then complete others.

always spawn a worker with the task it was supposed to complete

---

pool/context_pool.go
pool/context_pool_test.go
pool/result_context_pool.go
pool/result_context_pool_test.go

In https://github.com/sourcegraph/conc/pull/104, a "FailFast" option is likely going to be added to iterators that, on error, stops running additional tasks and returns the error that caused the first failure. 
"FailFast" seems is a pretty standard description for this behavior, and combining two common options into a single option with a more discoverable name seems like a nice thing to do before 1.0.

Add `WithFailFast()`

---

iter/map.go

We use the new error facilities when built with go 1.20, so this TODO no longer applies.

Remove outdated TODO

---

iter/export_test.go
iter/iter_test.go
iter/map_test.go
panics/panics_test.go
panics/try_test.go
pool/context_pool_test.go
pool/error_pool_test.go
pool/pool_test.go
pool/result_context_pool_test.go
pool/result_error_pool_test.go
pool/result_pool_test.go
stream/stream_test.go
waitgroup_test.go

The main reason for this PR was to make the examples in documentation
copy-pasteable, but there are some additional benefits too.
For example, the pool example before this change:
```go
p := New().WithMaxGoroutines(3)
for i := 0; i < 5; i++ {
p.Go(func() {
fmt.Println("conc")
})
}
p.Wait()
```
and after:
```go
p := pool.New().WithMaxGoroutines(3) // has package name
for i := 0; i < 5; i++ {
p.Go(func() {
fmt.Println("conc")
})
}
p.Wait()
```
The function `defaultMaxGoroutines` in `iter` package had to be exported because it was used from the tests.

Use *_test packages to make examples copy-pasteable

---

iter/map.go

This fixes `MapErr` so that it does not create recursive `joinError`s. By repeatedly calling `errors.Join(`, we create a nested set of `joinError`s rather than a single, flat `joinError`. Then, when `Error()` is called, it allocates a new string for each nested error because `joinError` calls `Error()` recursively on each of its children.
Instead, this PR updates `MapErr` to just collect a slice of errors and return the flat joined error.

Multierror: join errors at the end

---

pool/result_context_pool.go
pool/result_context_pool_test.go
pool/result_error_pool.go
pool/result_error_pool_test.go
pool/result_pool.go
pool/result_pool_test.go

This PR makes the order of results in a `Result.*Pool` deterministic so that the order of the result slice corresponds with the order of tasks submitted. As an example of why this would be useful, it makes it easy to rewrite `iter.Map` in terms of `ResultPool`. Additionally, it's a generally nice and intuitive property to be able to match the index of the result slice with the index of the input slice. 
Comments inline.

Make result order deterministic

---

pool/error_pool.go
pool/error_pool_test.go
pool/result_context_pool.go
pool/result_context_pool_test.go
pool/result_error_pool.go
pool/result_error_pool_test.go
pool/result_pool.go
pool/result_pool_test.go

This updates the pool types that collect results and errors to reset on `Wait` so they are reusable once waited on. Previously, if a pool was reused, the returned values of `Wait()` would contain the aggregated set of all previous uses. This wasn't explicitly a guarantee of the library before, but it does make it operate more like `sync.WaitGroup` and it's easy to do, so I think it's a positive change.
Fixes https://github.com/sourcegraph/conc/issues/128
Stacked on https://github.com/sourcegraph/conc/pull/126

Reusable pools

---

.github/workflows/go.yml
README.md
go.mod
go.sum
internal/multierror/multierror_go119.go
internal/multierror/multierror_go120.go
iter/map.go
iter/map_test.go
pool/error_pool.go

This PR removes the dependency on `go.uber.org/multierror` in favor of the multierror functionality included in go 1.20. 
As a consequence, this removes support for go versions earlier than go 1.20. In order to maintain the standard "two minor versions" support policy, this change will not be released (likely in a 1.0 version) until go 1.22 is released.

Exclusively use go1.20 multierrors

---

.github/workflows/bench.yml
.github/workflows/main.yml
Makefile

This PR:
- Adds a Makefile with `make test` and `make lint` and `make bench`
- Adds a new workflow for `main` that runs benchmarks and saves them
- Adds a new workflow for PRs that runs benchmarks and compares against `main`. When a benchmark regression occurs, it should fail the workflow, like so:

feat: add Makefile and run benchmarks as part of PRs
